version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_contraseña
      POSTGRES_DB: tu_base_de_datos
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#    volumes:
#      - db_data:/var/lib/postgresql/data
#volume:
#  db_data: